### PR TITLE
Compatibility with FFMPEG 7.0

### LINKED ISSUE #57: alsa-plugins-1.2.7.1 fails to compile against latest ffmpeg git
```
libtool: compile:  x86_64-pc-linux-gnu-gcc -m32 -mfpmath=sse -DHAVE_CONFIG_H -I. -I/var/tmp/portage/media-plugins/alsa-plugins-1.2.7.1-r1/work/alsa-plugins-1.2.7.1/a52 -I.. -DNDEBUG -Wall -g -march=native -mtune=native -O2 -pipe -c /var/tmp/portage/media-plugins/alsa-plugins-1.2.7.1-r1/work/alsa-plugins-1.2.7.1/a52/pcm_a52.c  -fPIC -DPIC -o .libs/pcm_a52.o
/var/tmp/portage/media-plugins/alsa-plugins-1.2.7.1-r1/work/alsa-plugins-1.2.7.1/a52/pcm_a52.c: In function 'a52_free':
/var/tmp/portage/media-plugins/alsa-plugins-1.2.7.1-r1/work/alsa-plugins-1.2.7.1/a52/pcm_a52.c:631:17: warning: 'avcodec_close' is deprecated [-Wdeprecated-declarations]
  631 |                 avcodec_close(rec->avctx);
      |                 ^~~~~~~~~~~~~
In file included from /var/tmp/portage/media-plugins/alsa-plugins-1.2.7.1-r1/work/alsa-plugins-1.2.7.1/a52/pcm_a52.c:28:
/usr/include/libavcodec/avcodec.h:2374:5: note: declared here
 2374 | int avcodec_close(AVCodecContext *avctx);
      |     ^~~~~~~~~~~~~
/var/tmp/portage/media-plugins/alsa-plugins-1.2.7.1-r1/work/alsa-plugins-1.2.7.1/a52/pcm_a52.c: In function 'set_channel_layout':
/var/tmp/portage/media-plugins/alsa-plugins-1.2.7.1-r1/work/alsa-plugins-1.2.7.1/a52/pcm_a52.c:672:29: error: 'AVCodecContext' has no member named 'channel_layout'; did you mean 'ch_layout'?
  672 |                 rec->avctx->channel_layout = AV_CH_LAYOUT_STEREO;
      |                             ^~~~~~~~~~~~~~
      |                             ch_layout
/var/tmp/portage/media-plugins/alsa-plugins-1.2.7.1-r1/work/alsa-plugins-1.2.7.1/a52/pcm_a52.c:675:29: error: 'AVCodecContext' has no member named 'channel_layout'; did you mean 'ch_layout'?
  675 |                 rec->avctx->channel_layout = AV_CH_LAYOUT_QUAD;
      |                             ^~~~~~~~~~~~~~
      |                             ch_layout
/var/tmp/portage/media-plugins/alsa-plugins-1.2.7.1-r1/work/alsa-plugins-1.2.7.1/a52/pcm_a52.c:678:29: error: 'AVCodecContext' has no member named 'channel_layout'; did you mean 'ch_layout'?
  678 |                 rec->avctx->channel_layout = AV_CH_LAYOUT_5POINT1;
      |                             ^~~~~~~~~~~~~~
      |                             ch_layout
/var/tmp/portage/media-plugins/alsa-plugins-1.2.7.1-r1/work/alsa-plugins-1.2.7.1/a52/pcm_a52.c: In function 'alloc_input_buffer':
/var/tmp/portage/media-plugins/alsa-plugins-1.2.7.1-r1/work/alsa-plugins-1.2.7.1/a52/pcm_a52.c:698:19: error: 'AVFrame' has no member named 'channels'
  698 |         rec->frame->channels = rec->avctx->channels;
      |                   ^~
/var/tmp/portage/media-plugins/alsa-plugins-1.2.7.1-r1/work/alsa-plugins-1.2.7.1/a52/pcm_a52.c:698:42: error: 'AVCodecContext' has no member named 'channels'
  698 |         rec->frame->channels = rec->avctx->channels;
      |                                          ^~
/var/tmp/portage/media-plugins/alsa-plugins-1.2.7.1-r1/work/alsa-plugins-1.2.7.1/a52/pcm_a52.c:699:21: error: 'AVFrame' has no member named 'channel_layout'; did you mean 'ch_layout'?
  699 |         rec->frame->channel_layout = rec->avctx->channel_layout;
      |                     ^~~~~~~~~~~~~~
      |                     ch_layout
/var/tmp/portage/media-plugins/alsa-plugins-1.2.7.1-r1/work/alsa-plugins-1.2.7.1/a52/pcm_a52.c:699:50: error: 'AVCodecContext' has no member named 'channel_layout'; did you mean 'ch_layout'?
  699 |         rec->frame->channel_layout = rec->avctx->channel_layout;
      |                                                  ^~~~~~~~~~~~~~
      |                                                  ch_layout
/var/tmp/portage/media-plugins/alsa-plugins-1.2.7.1-r1/work/alsa-plugins-1.2.7.1/a52/pcm_a52.c: In function 'a52_prepare':
/var/tmp/portage/media-plugins/alsa-plugins-1.2.7.1-r1/work/alsa-plugins-1.2.7.1/a52/pcm_a52.c:734:19: error: 'AVCodecContext' has no member named 'channels'
  734 |         rec->avctx->channels = io->channels;
      |                   ^~
/var/tmp/portage/media-plugins/alsa-plugins-1.2.7.1-r1/work/alsa-plugins-1.2.7.1/a52/pcm_a52.c: In function '_snd_pcm_a52_open':
/var/tmp/portage/media-plugins/alsa-plugins-1.2.7.1-r1/work/alsa-plugins-1.2.7.1/a52/pcm_a52.c:1124:28: warning: assignment discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
 1124 |                 rec->codec = avcodec_find_encoder_by_name(avcodec);
      |                            ^
/var/tmp/portage/media-plugins/alsa-plugins-1.2.7.1-r1/work/alsa-plugins-1.2.7.1/a52/pcm_a52.c:1126:28: warning: assignment discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
 1126 |                 rec->codec = avcodec_find_encoder_by_name("ac3_fixed");
      |                            ^
/var/tmp/portage/media-plugins/alsa-plugins-1.2.7.1-r1/work/alsa-plugins-1.2.7.1/a52/pcm_a52.c:1128:36: warning: assignment discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
 1128 |                         rec->codec = avcodec_find_encoder_by_name("ac3");
      |                                    ^
/var/tmp/portage/media-plugins/alsa-plugins-1.2.7.1-r1/work/alsa-plugins-1.2.7.1/a52/pcm_a52.c:1131:28: warning: assignment discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
 1131 |                 rec->codec = avcodec_find_encoder(AV_CODEC_ID_AC3);
      |                            ^
make[2]: *** [Makefile:469: pcm_a52.lo] Error 1
make[2]: Leaving directory '/var/tmp/portage/media-plugins/alsa-plugins-1.2.7.1-r1/work/alsa-plugins-1.2.7.1-abi_x86_32.x86/a52'
make[1]: *** [Makefile:445: all-recursive] Error 1
make[1]: Leaving directory '/var/tmp/portage/media-plugins/alsa-plugins-1.2.7.1-r1/work/alsa-plugins-1.2.7.1-abi_x86_32.x86'
make: *** [Makefile:377: all] Error 2
 * ERROR: media-plugins/alsa-plugins-1.2.7.1-r1::gentoo failed (compile phase):
 *   emake failed
```

### PR DESCRIPTION
**Pull request by eclipseo**
channel_layout has been replace with ch_layout

avcodec_close has been deprecated in favor of avcodec_free_context

Fix #57

### CODE REVIEW

**Comment by fhloston** [comment]
This breaks the a52 encoder profile for me:


```
ALSA device open 'plug:SLAVE='a52:0'' playback: 0x5610a26b99d0
[ac3_fixed @ 0x5610a26af040] Specified channel layout '6 channels' is not supported by the ac3_fixed encoder
[ac3_fixed @ 0x5610a26af040] Supported channel layouts:
[ac3_fixed @ 0x5610a26af040]   mono
[ac3_fixed @ 0x5610a26af040]   stereo
[ac3_fixed @ 0x5610a26af040]   3.0(back)
[ac3_fixed @ 0x5610a26af040]   3.0
[ac3_fixed @ 0x5610a26af040]   quad(side)
[ac3_fixed @ 0x5610a26af040]   quad
[ac3_fixed @ 0x5610a26af040]   4.0
[ac3_fixed @ 0x5610a26af040]   5.0(side)
[ac3_fixed @ 0x5610a26af040]   5.0
[ac3_fixed @ 0x5610a26af040]   2 channels (FC+LFE)
[ac3_fixed @ 0x5610a26af040]   2.1
[ac3_fixed @ 0x5610a26af040]   4 channels (FL+FR+LFE+BC)
[ac3_fixed @ 0x5610a26af040]   3.1
[ac3_fixed @ 0x5610a26af040]   4.1
[ac3_fixed @ 0x5610a26af040]   5.1(side)
[ac3_fixed @ 0x5610a26af040]   5.1
```

**Comment by eclipseo** [comment]
@fhloston This seems unrelated to this patch, ac3_fixed has always only supported this.


https://github.com/FFmpeg/FFmpeg/commit/65ddc74988245a01421a63c5cffa4d900c47117c


```C
/**
 * List of supported channel layouts.
 */
const AVChannelLayout ff_ac3_ch_layouts[19] = {
    AV_CHANNEL_LAYOUT_MONO,
    AV_CHANNEL_LAYOUT_STEREO,
    AV_CHANNEL_LAYOUT_2_1,
    AV_CHANNEL_LAYOUT_SURROUND,
    AV_CHANNEL_LAYOUT_2_2,
    AV_CHANNEL_LAYOUT_QUAD,
    AV_CHANNEL_LAYOUT_4POINT0,
    AV_CHANNEL_LAYOUT_5POINT0,
    AV_CHANNEL_LAYOUT_5POINT0_BACK,
    {
        .nb_channels = 2,
        .order       = AV_CHANNEL_ORDER_NATIVE,
        .u.mask      = AV_CH_LAYOUT_MONO | AV_CH_LOW_FREQUENCY,
    },
    {
        .nb_channels = 3,
        .order       = AV_CHANNEL_ORDER_NATIVE,
        .u.mask      = AV_CH_LAYOUT_STEREO | AV_CH_LOW_FREQUENCY,
    },
    {
        .nb_channels = 4,
        .order       = AV_CHANNEL_ORDER_NATIVE,
        .u.mask      = AV_CH_LAYOUT_2_1 | AV_CH_LOW_FREQUENCY,
    },
    {
        .nb_channels = 4,
        .order       = AV_CHANNEL_ORDER_NATIVE,
        .u.mask      = AV_CH_LAYOUT_SURROUND | AV_CH_LOW_FREQUENCY,
    },
    {
        .nb_channels = 5,
        .order       = AV_CHANNEL_ORDER_NATIVE,
        .u.mask      = AV_CH_LAYOUT_4POINT0 | AV_CH_LOW_FREQUENCY,
    },
    AV_CHANNEL_LAYOUT_5POINT1,
    AV_CHANNEL_LAYOUT_5POINT1_BACK,
    { 0 },
};
```

Though it should probably use the avcodec codec, but nothing I have changed should impact this.

**Comment by fhloston** [comment]
I cannot tell... previous version with ffmpeg6 just works though.

**Comment by eclipseo** [comment]
> I cannot tell... previous version with ffmpeg6 just works though.

Could you try with last push? Maybe it is an issue with mapping the channels with the new layout.

**Comment by fhloston** [comment]
That seems to have done the trick!

I have a working a52 profile.

:tada:

**Pull request closed without merging**
