### PR TITLE
jack: add option to allow non-jack-aligned period size

### PR DESCRIPTION
**Pull request by aditpape**
Commit 72337f1dcb2df6a2b7fdae93e88d7dd3a7e97ab4 forces ALSA period size
to be exact multiple of the JACK daemon period size.
There are good reasons to align the period size, but completely disallowing non aligned periods is too restrictive.
This patch adds an option "align_psize" which allows to optionally revert to original behavior.

Signed-off-by: Andreas Pape <apape@de.adit-jv.com>

### CODE REVIEW

**Comment by aditpape** [comment]
@perexg, @tiwai : any objections or doubts on this PR?

**Comment by aditpape** [comment]
This PR is also an alternate solution for issue #12 .
(The proposed solution for issue #12 itself does not conflict with this PR and could still be considered in addition..)

**Comment by aditpape** [comment]
@perexg : sorry to ping again...
Is there a chance to get it in, now that we even have a linked issue report?
THX,
Andreas

**Comment by perexg** [comment]
Merged in 3b6d4fad8ac8361262a6e5efb4b614b1b3dfe764 . Thank you.

**Pull request closed without merging**
